# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import harness_pb2 as harness__pb2


class Portal2HarnessStub(object):
    """The core service for external game control
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitialHandshake = channel.unary_unary(
                '/portal2_harness.Portal2Harness/InitialHandshake',
                request_serializer=harness__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=harness__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/portal2_harness.Portal2Harness/Observe',
                request_serializer=harness__pb2.Empty.SerializeToString,
                response_deserializer=harness__pb2.GameState.FromString,
                _registered_method=True)
        self.Act = channel.unary_unary(
                '/portal2_harness.Portal2Harness/Act',
                request_serializer=harness__pb2.ActionRequest.SerializeToString,
                response_deserializer=harness__pb2.ActionResponse.FromString,
                _registered_method=True)


class Portal2HarnessServicer(object):
    """The core service for external game control
    """

    def InitialHandshake(self, request, context):
        """Handshake to verify connection and sync game constants
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Get the current state of the player and world
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Act(self, request, context):
        """Send an action to be executed in the next game tick
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Portal2HarnessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitialHandshake': grpc.unary_unary_rpc_method_handler(
                    servicer.InitialHandshake,
                    request_deserializer=harness__pb2.HandshakeRequest.FromString,
                    response_serializer=harness__pb2.HandshakeResponse.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=harness__pb2.Empty.FromString,
                    response_serializer=harness__pb2.GameState.SerializeToString,
            ),
            'Act': grpc.unary_unary_rpc_method_handler(
                    servicer.Act,
                    request_deserializer=harness__pb2.ActionRequest.FromString,
                    response_serializer=harness__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'portal2_harness.Portal2Harness', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('portal2_harness.Portal2Harness', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Portal2Harness(object):
    """The core service for external game control
    """

    @staticmethod
    def InitialHandshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portal2_harness.Portal2Harness/InitialHandshake',
            harness__pb2.HandshakeRequest.SerializeToString,
            harness__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portal2_harness.Portal2Harness/Observe',
            harness__pb2.Empty.SerializeToString,
            harness__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portal2_harness.Portal2Harness/Act',
            harness__pb2.ActionRequest.SerializeToString,
            harness__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
