# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'harness.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rharness.proto\x12\x0fportal2_harness\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\xc8\x01\n\tGameState\x12*\n\x08position\x18\x01 \x01(\x0b\x32\x18.portal2_harness.Vector3\x12*\n\x08velocity\x18\x02 \x01(\x0b\x32\x18.portal2_harness.Vector3\x12(\n\x06\x63\x61mera\x18\x03 \x01(\x0b\x32\x18.portal2_harness.Vector3\x12\x0e\n\x06health\x18\x04 \x01(\x05\x12\x14\n\x0cis_crouching\x18\x05 \x01(\x08\x12\x13\n\x0bserver_tick\x18\x06 \x01(\x05\"\x95\x02\n\rActionRequest\x12\x13\n\x0bkey_forward\x18\x01 \x01(\x08\x12\x10\n\x08key_left\x18\x02 \x01(\x08\x12\x14\n\x0ckey_backward\x18\x03 \x01(\x08\x12\x11\n\tkey_right\x18\x04 \x01(\x08\x12\x0f\n\x07key_use\x18\x05 \x01(\x08\x12\x12\n\nkey_zoomin\x18\x06 \x01(\x08\x12\x13\n\x0bkey_zoomout\x18\x07 \x01(\x08\x12\x12\n\nkey_crouch\x18\x08 \x01(\x08\x12\x16\n\x0eportal_primary\x18\t \x01(\x08\x12\x18\n\x10portal_secondary\x18\n \x01(\x08\x12\x10\n\x08key_jump\x18\x0b \x01(\x08\x12\x10\n\x08mouse_dx\x18\x0c \x01(\x02\x12\x10\n\x08mouse_dy\x18\r \x01(\x02\"8\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"=\n\x10HandshakeRequest\x12\x16\n\x0e\x63lient_version\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\";\n\x11HandshakeResponse\x12\x14\n\x0cgame_version\x18\x01 \x01(\t\x12\x10\n\x08map_name\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xf2\x01\n\x0ePortal2Harness\x12Y\n\x10InitialHandshake\x12!.portal2_harness.HandshakeRequest\x1a\".portal2_harness.HandshakeResponse\x12=\n\x07Observe\x12\x16.portal2_harness.Empty\x1a\x1a.portal2_harness.GameState\x12\x46\n\x03\x41\x63t\x12\x1e.portal2_harness.ActionRequest\x1a\x1f.portal2_harness.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'harness_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR3']._serialized_start=34
  _globals['_VECTOR3']._serialized_end=76
  _globals['_GAMESTATE']._serialized_start=79
  _globals['_GAMESTATE']._serialized_end=279
  _globals['_ACTIONREQUEST']._serialized_start=282
  _globals['_ACTIONREQUEST']._serialized_end=559
  _globals['_ACTIONRESPONSE']._serialized_start=561
  _globals['_ACTIONRESPONSE']._serialized_end=617
  _globals['_HANDSHAKEREQUEST']._serialized_start=619
  _globals['_HANDSHAKEREQUEST']._serialized_end=680
  _globals['_HANDSHAKERESPONSE']._serialized_start=682
  _globals['_HANDSHAKERESPONSE']._serialized_end=741
  _globals['_EMPTY']._serialized_start=743
  _globals['_EMPTY']._serialized_end=750
  _globals['_PORTAL2HARNESS']._serialized_start=753
  _globals['_PORTAL2HARNESS']._serialized_end=995
# @@protoc_insertion_point(module_scope)
