// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: harness.proto
#ifndef GRPC_harness_2eproto__INCLUDED
#define GRPC_harness_2eproto__INCLUDED

#include "harness.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace portal2_harness {

// The core service for external game control
class Portal2Harness final {
 public:
  static constexpr char const* service_full_name() {
    return "portal2_harness.Portal2Harness";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Handshake to verify connection and sync game constants
    virtual ::grpc::Status InitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::portal2_harness::HandshakeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::HandshakeResponse>> AsyncInitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::HandshakeResponse>>(AsyncInitialHandshakeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::HandshakeResponse>> PrepareAsyncInitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::HandshakeResponse>>(PrepareAsyncInitialHandshakeRaw(context, request, cq));
    }
    // Get the current state of the player and world
    virtual ::grpc::Status Observe(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::portal2_harness::GameState* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::GameState>> AsyncObserve(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::GameState>>(AsyncObserveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::GameState>> PrepareAsyncObserve(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::GameState>>(PrepareAsyncObserveRaw(context, request, cq));
    }
    // Send an action to be executed in the next game tick
    virtual ::grpc::Status Act(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::portal2_harness::ActionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ActionResponse>> AsyncAct(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ActionResponse>>(AsyncActRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ActionResponse>> PrepareAsyncAct(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ActionResponse>>(PrepareAsyncActRaw(context, request, cq));
    }
    // Execute an arbitrary console command (DANGEROUS - testing only)
    virtual ::grpc::Status ExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::portal2_harness::CommandResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::CommandResponse>> AsyncExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::CommandResponse>>(AsyncExecuteCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::CommandResponse>> PrepareAsyncExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::CommandResponse>>(PrepareAsyncExecuteCommandRaw(context, request, cq));
    }
    // Reset the episode: restart level, wait for warmup, return initial state
    virtual ::grpc::Status Reset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::portal2_harness::ResetResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ResetResponse>> AsyncReset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ResetResponse>>(AsyncResetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ResetResponse>> PrepareAsyncReset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ResetResponse>>(PrepareAsyncResetRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Handshake to verify connection and sync game constants
      virtual void InitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest* request, ::portal2_harness::HandshakeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest* request, ::portal2_harness::HandshakeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get the current state of the player and world
      virtual void Observe(::grpc::ClientContext* context, const ::portal2_harness::Empty* request, ::portal2_harness::GameState* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Observe(::grpc::ClientContext* context, const ::portal2_harness::Empty* request, ::portal2_harness::GameState* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Send an action to be executed in the next game tick
      virtual void Act(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest* request, ::portal2_harness::ActionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Act(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest* request, ::portal2_harness::ActionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Execute an arbitrary console command (DANGEROUS - testing only)
      virtual void ExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest* request, ::portal2_harness::CommandResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest* request, ::portal2_harness::CommandResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Reset the episode: restart level, wait for warmup, return initial state
      virtual void Reset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest* request, ::portal2_harness::ResetResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Reset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest* request, ::portal2_harness::ResetResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::HandshakeResponse>* AsyncInitialHandshakeRaw(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::HandshakeResponse>* PrepareAsyncInitialHandshakeRaw(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::GameState>* AsyncObserveRaw(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::GameState>* PrepareAsyncObserveRaw(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ActionResponse>* AsyncActRaw(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ActionResponse>* PrepareAsyncActRaw(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::CommandResponse>* AsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::CommandResponse>* PrepareAsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ResetResponse>* AsyncResetRaw(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::portal2_harness::ResetResponse>* PrepareAsyncResetRaw(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status InitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::portal2_harness::HandshakeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::HandshakeResponse>> AsyncInitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::HandshakeResponse>>(AsyncInitialHandshakeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::HandshakeResponse>> PrepareAsyncInitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::HandshakeResponse>>(PrepareAsyncInitialHandshakeRaw(context, request, cq));
    }
    ::grpc::Status Observe(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::portal2_harness::GameState* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::GameState>> AsyncObserve(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::GameState>>(AsyncObserveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::GameState>> PrepareAsyncObserve(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::GameState>>(PrepareAsyncObserveRaw(context, request, cq));
    }
    ::grpc::Status Act(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::portal2_harness::ActionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::ActionResponse>> AsyncAct(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::ActionResponse>>(AsyncActRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::ActionResponse>> PrepareAsyncAct(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::ActionResponse>>(PrepareAsyncActRaw(context, request, cq));
    }
    ::grpc::Status ExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::portal2_harness::CommandResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::CommandResponse>> AsyncExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::CommandResponse>>(AsyncExecuteCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::CommandResponse>> PrepareAsyncExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::CommandResponse>>(PrepareAsyncExecuteCommandRaw(context, request, cq));
    }
    ::grpc::Status Reset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::portal2_harness::ResetResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::ResetResponse>> AsyncReset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::ResetResponse>>(AsyncResetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::ResetResponse>> PrepareAsyncReset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::portal2_harness::ResetResponse>>(PrepareAsyncResetRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void InitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest* request, ::portal2_harness::HandshakeResponse* response, std::function<void(::grpc::Status)>) override;
      void InitialHandshake(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest* request, ::portal2_harness::HandshakeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Observe(::grpc::ClientContext* context, const ::portal2_harness::Empty* request, ::portal2_harness::GameState* response, std::function<void(::grpc::Status)>) override;
      void Observe(::grpc::ClientContext* context, const ::portal2_harness::Empty* request, ::portal2_harness::GameState* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Act(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest* request, ::portal2_harness::ActionResponse* response, std::function<void(::grpc::Status)>) override;
      void Act(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest* request, ::portal2_harness::ActionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest* request, ::portal2_harness::CommandResponse* response, std::function<void(::grpc::Status)>) override;
      void ExecuteCommand(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest* request, ::portal2_harness::CommandResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Reset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest* request, ::portal2_harness::ResetResponse* response, std::function<void(::grpc::Status)>) override;
      void Reset(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest* request, ::portal2_harness::ResetResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::HandshakeResponse>* AsyncInitialHandshakeRaw(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::HandshakeResponse>* PrepareAsyncInitialHandshakeRaw(::grpc::ClientContext* context, const ::portal2_harness::HandshakeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::GameState>* AsyncObserveRaw(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::GameState>* PrepareAsyncObserveRaw(::grpc::ClientContext* context, const ::portal2_harness::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::ActionResponse>* AsyncActRaw(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::ActionResponse>* PrepareAsyncActRaw(::grpc::ClientContext* context, const ::portal2_harness::ActionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::CommandResponse>* AsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::CommandResponse>* PrepareAsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::portal2_harness::CommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::ResetResponse>* AsyncResetRaw(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::portal2_harness::ResetResponse>* PrepareAsyncResetRaw(::grpc::ClientContext* context, const ::portal2_harness::ResetRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_InitialHandshake_;
    const ::grpc::internal::RpcMethod rpcmethod_Observe_;
    const ::grpc::internal::RpcMethod rpcmethod_Act_;
    const ::grpc::internal::RpcMethod rpcmethod_ExecuteCommand_;
    const ::grpc::internal::RpcMethod rpcmethod_Reset_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Handshake to verify connection and sync game constants
    virtual ::grpc::Status InitialHandshake(::grpc::ServerContext* context, const ::portal2_harness::HandshakeRequest* request, ::portal2_harness::HandshakeResponse* response);
    // Get the current state of the player and world
    virtual ::grpc::Status Observe(::grpc::ServerContext* context, const ::portal2_harness::Empty* request, ::portal2_harness::GameState* response);
    // Send an action to be executed in the next game tick
    virtual ::grpc::Status Act(::grpc::ServerContext* context, const ::portal2_harness::ActionRequest* request, ::portal2_harness::ActionResponse* response);
    // Execute an arbitrary console command (DANGEROUS - testing only)
    virtual ::grpc::Status ExecuteCommand(::grpc::ServerContext* context, const ::portal2_harness::CommandRequest* request, ::portal2_harness::CommandResponse* response);
    // Reset the episode: restart level, wait for warmup, return initial state
    virtual ::grpc::Status Reset(::grpc::ServerContext* context, const ::portal2_harness::ResetRequest* request, ::portal2_harness::ResetResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_InitialHandshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InitialHandshake() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_InitialHandshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitialHandshake(::grpc::ServerContext* /*context*/, const ::portal2_harness::HandshakeRequest* /*request*/, ::portal2_harness::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitialHandshake(::grpc::ServerContext* context, ::portal2_harness::HandshakeRequest* request, ::grpc::ServerAsyncResponseWriter< ::portal2_harness::HandshakeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Observe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Observe() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Observe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Observe(::grpc::ServerContext* /*context*/, const ::portal2_harness::Empty* /*request*/, ::portal2_harness::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestObserve(::grpc::ServerContext* context, ::portal2_harness::Empty* request, ::grpc::ServerAsyncResponseWriter< ::portal2_harness::GameState>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Act : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Act() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Act() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Act(::grpc::ServerContext* /*context*/, const ::portal2_harness::ActionRequest* /*request*/, ::portal2_harness::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAct(::grpc::ServerContext* context, ::portal2_harness::ActionRequest* request, ::grpc::ServerAsyncResponseWriter< ::portal2_harness::ActionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::portal2_harness::CommandRequest* /*request*/, ::portal2_harness::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteCommand(::grpc::ServerContext* context, ::portal2_harness::CommandRequest* request, ::grpc::ServerAsyncResponseWriter< ::portal2_harness::CommandResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Reset() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::portal2_harness::ResetRequest* /*request*/, ::portal2_harness::ResetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReset(::grpc::ServerContext* context, ::portal2_harness::ResetRequest* request, ::grpc::ServerAsyncResponseWriter< ::portal2_harness::ResetResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_InitialHandshake<WithAsyncMethod_Observe<WithAsyncMethod_Act<WithAsyncMethod_ExecuteCommand<WithAsyncMethod_Reset<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_InitialHandshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InitialHandshake() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::portal2_harness::HandshakeRequest, ::portal2_harness::HandshakeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::portal2_harness::HandshakeRequest* request, ::portal2_harness::HandshakeResponse* response) { return this->InitialHandshake(context, request, response); }));}
    void SetMessageAllocatorFor_InitialHandshake(
        ::grpc::MessageAllocator< ::portal2_harness::HandshakeRequest, ::portal2_harness::HandshakeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::portal2_harness::HandshakeRequest, ::portal2_harness::HandshakeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_InitialHandshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitialHandshake(::grpc::ServerContext* /*context*/, const ::portal2_harness::HandshakeRequest* /*request*/, ::portal2_harness::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InitialHandshake(
      ::grpc::CallbackServerContext* /*context*/, const ::portal2_harness::HandshakeRequest* /*request*/, ::portal2_harness::HandshakeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Observe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Observe() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::portal2_harness::Empty, ::portal2_harness::GameState>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::portal2_harness::Empty* request, ::portal2_harness::GameState* response) { return this->Observe(context, request, response); }));}
    void SetMessageAllocatorFor_Observe(
        ::grpc::MessageAllocator< ::portal2_harness::Empty, ::portal2_harness::GameState>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::portal2_harness::Empty, ::portal2_harness::GameState>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Observe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Observe(::grpc::ServerContext* /*context*/, const ::portal2_harness::Empty* /*request*/, ::portal2_harness::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Observe(
      ::grpc::CallbackServerContext* /*context*/, const ::portal2_harness::Empty* /*request*/, ::portal2_harness::GameState* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Act : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Act() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::portal2_harness::ActionRequest, ::portal2_harness::ActionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::portal2_harness::ActionRequest* request, ::portal2_harness::ActionResponse* response) { return this->Act(context, request, response); }));}
    void SetMessageAllocatorFor_Act(
        ::grpc::MessageAllocator< ::portal2_harness::ActionRequest, ::portal2_harness::ActionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::portal2_harness::ActionRequest, ::portal2_harness::ActionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Act() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Act(::grpc::ServerContext* /*context*/, const ::portal2_harness::ActionRequest* /*request*/, ::portal2_harness::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Act(
      ::grpc::CallbackServerContext* /*context*/, const ::portal2_harness::ActionRequest* /*request*/, ::portal2_harness::ActionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::portal2_harness::CommandRequest, ::portal2_harness::CommandResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::portal2_harness::CommandRequest* request, ::portal2_harness::CommandResponse* response) { return this->ExecuteCommand(context, request, response); }));}
    void SetMessageAllocatorFor_ExecuteCommand(
        ::grpc::MessageAllocator< ::portal2_harness::CommandRequest, ::portal2_harness::CommandResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::portal2_harness::CommandRequest, ::portal2_harness::CommandResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::portal2_harness::CommandRequest* /*request*/, ::portal2_harness::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::portal2_harness::CommandRequest* /*request*/, ::portal2_harness::CommandResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Reset() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::portal2_harness::ResetRequest, ::portal2_harness::ResetResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::portal2_harness::ResetRequest* request, ::portal2_harness::ResetResponse* response) { return this->Reset(context, request, response); }));}
    void SetMessageAllocatorFor_Reset(
        ::grpc::MessageAllocator< ::portal2_harness::ResetRequest, ::portal2_harness::ResetResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::portal2_harness::ResetRequest, ::portal2_harness::ResetResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::portal2_harness::ResetRequest* /*request*/, ::portal2_harness::ResetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Reset(
      ::grpc::CallbackServerContext* /*context*/, const ::portal2_harness::ResetRequest* /*request*/, ::portal2_harness::ResetResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_InitialHandshake<WithCallbackMethod_Observe<WithCallbackMethod_Act<WithCallbackMethod_ExecuteCommand<WithCallbackMethod_Reset<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_InitialHandshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InitialHandshake() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_InitialHandshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitialHandshake(::grpc::ServerContext* /*context*/, const ::portal2_harness::HandshakeRequest* /*request*/, ::portal2_harness::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Observe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Observe() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Observe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Observe(::grpc::ServerContext* /*context*/, const ::portal2_harness::Empty* /*request*/, ::portal2_harness::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Act : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Act() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Act() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Act(::grpc::ServerContext* /*context*/, const ::portal2_harness::ActionRequest* /*request*/, ::portal2_harness::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::portal2_harness::CommandRequest* /*request*/, ::portal2_harness::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Reset() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::portal2_harness::ResetRequest* /*request*/, ::portal2_harness::ResetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_InitialHandshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InitialHandshake() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_InitialHandshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitialHandshake(::grpc::ServerContext* /*context*/, const ::portal2_harness::HandshakeRequest* /*request*/, ::portal2_harness::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitialHandshake(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Observe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Observe() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Observe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Observe(::grpc::ServerContext* /*context*/, const ::portal2_harness::Empty* /*request*/, ::portal2_harness::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestObserve(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Act : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Act() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Act() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Act(::grpc::ServerContext* /*context*/, const ::portal2_harness::ActionRequest* /*request*/, ::portal2_harness::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAct(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::portal2_harness::CommandRequest* /*request*/, ::portal2_harness::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteCommand(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Reset() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::portal2_harness::ResetRequest* /*request*/, ::portal2_harness::ResetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReset(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InitialHandshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InitialHandshake() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InitialHandshake(context, request, response); }));
    }
    ~WithRawCallbackMethod_InitialHandshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitialHandshake(::grpc::ServerContext* /*context*/, const ::portal2_harness::HandshakeRequest* /*request*/, ::portal2_harness::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InitialHandshake(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Observe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Observe() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Observe(context, request, response); }));
    }
    ~WithRawCallbackMethod_Observe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Observe(::grpc::ServerContext* /*context*/, const ::portal2_harness::Empty* /*request*/, ::portal2_harness::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Observe(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Act : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Act() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Act(context, request, response); }));
    }
    ~WithRawCallbackMethod_Act() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Act(::grpc::ServerContext* /*context*/, const ::portal2_harness::ActionRequest* /*request*/, ::portal2_harness::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Act(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExecuteCommand(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::portal2_harness::CommandRequest* /*request*/, ::portal2_harness::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Reset() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Reset(context, request, response); }));
    }
    ~WithRawCallbackMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::portal2_harness::ResetRequest* /*request*/, ::portal2_harness::ResetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Reset(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InitialHandshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InitialHandshake() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::portal2_harness::HandshakeRequest, ::portal2_harness::HandshakeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::portal2_harness::HandshakeRequest, ::portal2_harness::HandshakeResponse>* streamer) {
                       return this->StreamedInitialHandshake(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InitialHandshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InitialHandshake(::grpc::ServerContext* /*context*/, const ::portal2_harness::HandshakeRequest* /*request*/, ::portal2_harness::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInitialHandshake(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::portal2_harness::HandshakeRequest,::portal2_harness::HandshakeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Observe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Observe() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::portal2_harness::Empty, ::portal2_harness::GameState>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::portal2_harness::Empty, ::portal2_harness::GameState>* streamer) {
                       return this->StreamedObserve(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Observe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Observe(::grpc::ServerContext* /*context*/, const ::portal2_harness::Empty* /*request*/, ::portal2_harness::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedObserve(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::portal2_harness::Empty,::portal2_harness::GameState>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Act : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Act() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::portal2_harness::ActionRequest, ::portal2_harness::ActionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::portal2_harness::ActionRequest, ::portal2_harness::ActionResponse>* streamer) {
                       return this->StreamedAct(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Act() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Act(::grpc::ServerContext* /*context*/, const ::portal2_harness::ActionRequest* /*request*/, ::portal2_harness::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAct(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::portal2_harness::ActionRequest,::portal2_harness::ActionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::portal2_harness::CommandRequest, ::portal2_harness::CommandResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::portal2_harness::CommandRequest, ::portal2_harness::CommandResponse>* streamer) {
                       return this->StreamedExecuteCommand(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::portal2_harness::CommandRequest* /*request*/, ::portal2_harness::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecuteCommand(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::portal2_harness::CommandRequest,::portal2_harness::CommandResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Reset() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::portal2_harness::ResetRequest, ::portal2_harness::ResetResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::portal2_harness::ResetRequest, ::portal2_harness::ResetResponse>* streamer) {
                       return this->StreamedReset(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::portal2_harness::ResetRequest* /*request*/, ::portal2_harness::ResetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReset(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::portal2_harness::ResetRequest,::portal2_harness::ResetResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_InitialHandshake<WithStreamedUnaryMethod_Observe<WithStreamedUnaryMethod_Act<WithStreamedUnaryMethod_ExecuteCommand<WithStreamedUnaryMethod_Reset<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_InitialHandshake<WithStreamedUnaryMethod_Observe<WithStreamedUnaryMethod_Act<WithStreamedUnaryMethod_ExecuteCommand<WithStreamedUnaryMethod_Reset<Service > > > > > StreamedService;
};

}  // namespace portal2_harness


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_harness_2eproto__INCLUDED
