# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import harness_pb2 as harness__pb2


class Portal2HarnessStub(object):
    """The core service for external game control
    docs/harness.proto:Portal2Harness>
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitialHandshake = channel.unary_unary(
                '/portal2_harness.Portal2Harness/InitialHandshake',
                request_serializer=harness__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=harness__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/portal2_harness.Portal2Harness/Observe',
                request_serializer=harness__pb2.Empty.SerializeToString,
                response_deserializer=harness__pb2.GameState.FromString,
                _registered_method=True)
        self.Act = channel.unary_unary(
                '/portal2_harness.Portal2Harness/Act',
                request_serializer=harness__pb2.ActionRequest.SerializeToString,
                response_deserializer=harness__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/portal2_harness.Portal2Harness/ExecuteCommand',
                request_serializer=harness__pb2.CommandRequest.SerializeToString,
                response_deserializer=harness__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/portal2_harness.Portal2Harness/Reset',
                request_serializer=harness__pb2.ResetRequest.SerializeToString,
                response_deserializer=harness__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.AgentLoop = channel.stream_stream(
                '/portal2_harness.Portal2Harness/AgentLoop',
                request_serializer=harness__pb2.AgentMessage.SerializeToString,
                response_deserializer=harness__pb2.EnvironmentMessage.FromString,
                _registered_method=True)
        self.RenderDemo = channel.unary_unary(
                '/portal2_harness.Portal2Harness/RenderDemo',
                request_serializer=harness__pb2.RenderDemoRequest.SerializeToString,
                response_deserializer=harness__pb2.RenderDemoResponse.FromString,
                _registered_method=True)


class Portal2HarnessServicer(object):
    """The core service for external game control
    docs/harness.proto:Portal2Harness>
    """

    def InitialHandshake(self, request, context):
        """Handshake to verify connection and sync game constants
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Get the current state of the player and world
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Act(self, request, context):
        """Send an action to be executed in the next game tick
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Execute an arbitrary console command (DANGEROUS - testing only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset the episode: restart level, wait for warmup, return initial state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentLoop(self, request_iterator, context):
        """Bidirectional stream for high-performance agent loop
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderDemo(self, request, context):
        """First-class endpoint to render a demo file end-to-end.
        Initiates playback and blocks internally until rollout conversion concludes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Portal2HarnessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitialHandshake': grpc.unary_unary_rpc_method_handler(
                    servicer.InitialHandshake,
                    request_deserializer=harness__pb2.HandshakeRequest.FromString,
                    response_serializer=harness__pb2.HandshakeResponse.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=harness__pb2.Empty.FromString,
                    response_serializer=harness__pb2.GameState.SerializeToString,
            ),
            'Act': grpc.unary_unary_rpc_method_handler(
                    servicer.Act,
                    request_deserializer=harness__pb2.ActionRequest.FromString,
                    response_serializer=harness__pb2.ActionResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=harness__pb2.CommandRequest.FromString,
                    response_serializer=harness__pb2.CommandResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=harness__pb2.ResetRequest.FromString,
                    response_serializer=harness__pb2.ResetResponse.SerializeToString,
            ),
            'AgentLoop': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentLoop,
                    request_deserializer=harness__pb2.AgentMessage.FromString,
                    response_serializer=harness__pb2.EnvironmentMessage.SerializeToString,
            ),
            'RenderDemo': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderDemo,
                    request_deserializer=harness__pb2.RenderDemoRequest.FromString,
                    response_serializer=harness__pb2.RenderDemoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'portal2_harness.Portal2Harness', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('portal2_harness.Portal2Harness', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Portal2Harness(object):
    """The core service for external game control
    docs/harness.proto:Portal2Harness>
    """

    @staticmethod
    def InitialHandshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portal2_harness.Portal2Harness/InitialHandshake',
            harness__pb2.HandshakeRequest.SerializeToString,
            harness__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portal2_harness.Portal2Harness/Observe',
            harness__pb2.Empty.SerializeToString,
            harness__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portal2_harness.Portal2Harness/Act',
            harness__pb2.ActionRequest.SerializeToString,
            harness__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portal2_harness.Portal2Harness/ExecuteCommand',
            harness__pb2.CommandRequest.SerializeToString,
            harness__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portal2_harness.Portal2Harness/Reset',
            harness__pb2.ResetRequest.SerializeToString,
            harness__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentLoop(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/portal2_harness.Portal2Harness/AgentLoop',
            harness__pb2.AgentMessage.SerializeToString,
            harness__pb2.EnvironmentMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderDemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portal2_harness.Portal2Harness/RenderDemo',
            harness__pb2.RenderDemoRequest.SerializeToString,
            harness__pb2.RenderDemoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
